[project]
name = "fonkanfm50x"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastcrc>=0.3.4",
    "pyserial>=3.5",
]
